title: Extra OS 2019-1
version: V048-20190718 rms46
description: Proyek extra kuliah Sistem Operasi 2019-1
# show_downloads: true
google_analytics:
version: V047-20190718 rms46

theme: jekyll-theme-minimal
# theme: jekyll-theme-hacker
# theme: jekyll-theme-midnight

# Fixing the "No GitHub API authentication could be found" ??
github: [metadata]

